version: "3.8"

services:
  guardrails-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardrails-validator-api
    ports:
      - "8000:8000"
    environment:
      # Optional: Add environment variables here
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Optional: Mount volumes for persistent data
    # volumes:
    #   - ./logs:/app/logs
    networks:
      - guardrails-network

networks:
  guardrails-network:
    driver: bridge
